### ISSUE TITLE
フィードを登録するとき、いきなり追加するんじゃなくてプレビュー画面を挟みたい

### ISSUE THREAD

**Issue by june29** [kairan-app/feeeed#121]
追加したいウェブサイトやフィードの URL を Submit したとき「この内容で登録しますね？」のプレビューを挟みたい。そのときに、似ている(どうやって判定する？)フィードがすでに登録されていたら「こういうのもあるけど、これとは別に登録するのでいい？」を確認してあげた方が親切じゃろうと思う。

- https://github.com/kairan-app/feeeed/issues/61

特にポッドキャストは、ひとつの番組が複数のフィードを持っちゃうことが多くて「どうしてウェブはこうなった？」感があるんだけどそんなことを言っても仕方がないので、プレビューを活用するなどしていい感じに付き合っていきたい。

あとは、プレビュー画面的なものがあれば「フィードを追加して、そのまま購読もする」のようなチェックボックスも配置できるだろう。いろんな制御ができて便利かもしれない。

**Comment by june29** [comment]
- https://github.com/kairan-app/feeeed/issues/123

と絡めて考えると、プレビューについても複数フィードを前提に考えた方がいい？ しかし 100 個のフィードのプレビューってそもそも難しい気もするから、どうにもならないかも :thinking:

**Comment by sugiwe** [comment]
これはFigmaで何となくデザインを組んでみてイメージすると良いかもなやつですね👀

- 新規Channelコンポーネント
  - 画像、Description、URL
- （あれば）既にある類似Channelコンポーネント
  - 画像、Description、URL
- チェック＆Submit
  - 「Channel登録」「Add to my own」「Subscribe」などをそれぞれチェックしてまとめてSubmitかな

上記が、いちChannelあたりの塊としてあり、複数登録した場合には下にズラッと出てくる感じ？
しかしおっしゃるように、例えば5〜6個ならともかく100個一気に入れた時に処理の重さや体験として100個スクロールするのどうなん？って問題もありますね😇
複数登録は10個までみたいな制約をつけるとか？🤔

**Comment by june29** [comment]
どもども！

OPML インポートのときは、OPML の性質を鑑みて「プレビューなしでぜんぶ登録してぜんぶ購読状態にする」でいいか、と思ったりもしています :thinking:

textarea から複数の URL を一気に登録できるやつは、それこそ「一度に 10 個まで」とかにして、プレビューを成立させられるかもしれませんね :v:

**Comment by sugiwe** [comment]
確かに、OPML インポートと textarea からの複数登録でそれぞれ制限を変える、というのは良さそうな落とし所だと思いました😄

**Comment by juneboku** [comment]
プレビューは

- https://github.com/kairan-app/feeeed/pull/180

で実装したので、この Issue は Close しちゃおう。ここのコメント欄で話していたことの残りは

- https://github.com/kairan-app/feeeed/issues/123

で扱っていけると思います :v:
