### ISSUE TITLE
フィードはフィードでも自由に登録できないフィード、な〜んだ？

### ISSUE THREAD

**Issue by june29** [kairan-app/feeeed#125]
https://news.yahoo.co.jp/rss というページがあることを知った。

美術手帖のフィードを購読したいと思ったのだけれど公式サイト https://bijutsutecho.com にはフィードが見当たらなくて、適当に「美術手帖 rss」などとウェブ検索していたらたまたまYahoo!ニュースのページに漂着したってわけよ。

ところで、当該ページには下記の記述がある。

> 提供するRSSは個人利用にのみ使用することができます。
> RSSから取得した情報を用いたウェブサイトやアプリケーションなどのプログラムを作成して公開することは許可しておりません。また、RSSの再配信や再提供も許可しておりません。

これを読むと、個人で閉じて使うフィードリーダで活用するのはオッケーだけど、いま開発しているアプリケーションに登録するのはグレーに思えてくる。運営人間としてはリスクを感じるこれらフィード群は登録しないでおくのが無難だろう。

さて、

- 利用規約や注意事項によって「アプリケーションに登録しないでね」とされているフィード
- メンバーシップ限定など、権利を有する人たちだけがアクセスすることを想定されているフィード

などがぼくらの開発するアプリケーションに登録されるのはちょっと怖いんだけど、完全に防ぐことはむつかしい。どのように向き合っていくとよいだろうか？

**Comment by juneboku** [comment]
- https://github.com/kairan-app/feeeed/pull/180

にて、伝えるべきことは伝えられるようになったから、いったんこれでいいかな。なにか問題が起きたら考えましょう！
