### ISSUE TITLE
新着 Item の Webhook 通知で、Channel でグルーピングする版を試したい

### ISSUE THREAD

**Issue by june29** [kairan-app/feeeed#127]
- https://github.com/kairan-app/feeeed/pull/126

の表示をあれこれ試していて「Item は Channel でまとまっていると受け止めやすいかも」と思った :bulb:

今は Item をずらっと並べる形で通知しているけれど、Channel 単位でまとめて通知の表示コンポーネントを組み立ててあげたらベターな体験になるかしら、試してみたい。

関連して、Channel が追加された直後はそこに属するすべての Item の created_at が新しい状態になっちゃって、Item が 100 件あれば通知も 100 件になってしまう問題があって。Channel でまとめると、この問題に対する解決策にもなりうる。

**Comment by juneboku** [comment]
Slack の Incoming Webhook 向けの処理を実装して、それを Discord に流用する、って感じで進めるつもり :memo:

**Comment by juneboku** [comment]
- https://github.com/kairan-app/feeeed/pull/136

で進めているわよ〜 :dash:

**Comment by juneboku** [comment]
- Slack 版は https://github.com/kairan-app/feeeed/pull/136 で実装した
- Slack と Discord で共通の通知処理を使えるかと思ったけど目論見が外れた
- Discord 版は Discord 版で、これから実装するぞい

**Comment by juneboku** [comment]
意図した通りに動いていそうなので Close しちゃお :dash:
