### ISSUE TITLE
やっていき 2024-04

### ISSUE THREAD

**Issue by june29** [kairan-app/feeeed#128]
### あらすじ

- https://github.com/kairan-app/feeeed/issues/94

がよかったので、月ごとに Issue を立てて整理しながら進めていくのを引き続きやっていきます :cherry_blossom:

### やること (随時更新)

- [x] https://github.com/kairan-app/feeeed/pull/126
- [x] https://github.com/kairan-app/feeeed/pull/132
- [x] https://github.com/kairan-app/feeeed/pull/136
- [x] https://github.com/kairan-app/feeeed/issues/127
- [ ] メール通知機能を実装する (新着 Item/Pawprint を通知するやつ)
- [ ] https://github.com/kairan-app/feeeed/issues/121
- [ ] https://github.com/kairan-app/feeeed/issues/62
- [x] https://github.com/kairan-app/feeeed/issues/122
- [ ] https://github.com/kairan-app/feeeed/issues/135
- [x] https://github.com/kairan-app/feeeed/pull/131
- [x] ナビゲーション周りを整理する
  - [x] https://github.com/kairan-app/feeeed/pull/130
  - [x] https://github.com/kairan-app/feeeed/pull/133
- [x] https://github.com/kairan-app/feeeed/pull/137
- [x] https://github.com/kairan-app/feeeed/pull/139
- [x] 「About rururu」的なページの前段階として、世の中の似たようなページを参照したり、 rururu ならどういう章立てでどういう内容になりそうかを検討する
- [x] https://github.com/kairan-app/feeeed/pull/149
  - [x] 「非ログインの際にTOP冒頭にヒーローエリアを作る」も一緒に実装
- [ ] Pawprintsまわりの第二段階実装のスタイリングをする（figmaで検討しているもの）
- [ ] figma 整理
  - 今まで雑にfigmaでイメージを作ったり、figmaすっ飛ばしてスタイリングしたりしていたけど、そろそろ現時点の画面デザインを整理して、今後の検討にも活かしやすいようにしたい

**Comment by juneboku** [comment]
こんにちは、juneboku と申します〜！

**Comment by sugiwe** [comment]
わ〜い juneboku さん、熱烈歓迎します！

**Comment by juneboku** [comment]
4 月もありがとうございました！ :muscle:
