### ISSUE TITLE
Channel GroupsページのChannels表示上限が20になっているので増やしたい

### ISSUE THREAD

**Issue by sugiwe** [kairan-app/feeeed#328]
現状`limit(20)`の設定により、任意のChannel Groupsでチャンネルを20以上登録すると、新しく登録した20チャンネルが残って古いチャンネルが隠れてしまう😇
（ https://rururu.app/channel_groups/4 で、もっとチャンネル数あるよな？と思い発覚）

1. limitの数をある程度余裕のある数値にする
   - 100とか？今後のユースケースによってはまたオーバーするかもしれない。多めに200とかにしておく？
2. 単純にlimitの設定自体を削除する
   - 特定のChanel Groupへの登録が極端に増えるケースはあまり考えられない（あっても50とか100とか？）のでこれでも悪くはない。ただ、悪意を持って登録チャンネルを増やし続けられた場合には嬉しくないことになりそう
3. ページャーを設定する
   - 現状のItemsやChannelsのように50単位くらいでページャーを設定する。ただ、Channel GroupsページはChannelsの下にRecent Itemsもあるので、Channelをページャーで区切ったとき、2ページ目以降も1ページ目と同じRecent Itemsが表示されるのはなんとなく違和感ありそう

現時点では1で良いかな〜と思ったりしています！

**Comment by juneboku** [comment]
現状のデータの傾向なら limit ナシにしちゃってよさそう！

**Comment by sugiwe** [comment]
ありがとうございます、では追って limit を無くす PR を作ります〜！
