### ISSUE TITLE
ポッドキャストは、ひとつの番組が複数のフィードを持ちがち

### ISSUE THREAD

**Issue by june29** [kairan-app/feeeed#61]
たとえばキマグレエフエムだと

- Spotify for Podcasters のやつ
  - https://anchor.fm/s/31978840/podcast/rss
- LISTEN のやつ
  - https://listen.style/p/kimagurefm/rss

のように。これらがそれぞれ登録されると、アプリケーション上は二重に登録されたような見た目になる。どうしようね。

**Comment by june29** [comment]
いまは GUI から Channel を add するとそのまま追加されることになるが、確認画面をひとつ挟むことにして、

- あなたが追加しようとしている Channel は、こんな内容ですよ
- 類似の Channel としてすでにこんなものが登録されていますが、新規に追加しちゃっていいですか？

をプレビューしてあげるとちょっと親切かもな〜と思っている :bulb:

**Comment by juneboku** [comment]
- https://github.com/kairan-app/feeeed/pull/180

でプレビューを実装したので、これで防がれることもあるでしょう。あとは、間違えて登録したときに消せればいいので

- https://github.com/kairan-app/feeeed/issues/62

でカバーできる範囲かと思います。この Issue は Close しちゃいますね :dash:
