### ISSUE TITLE
やっていき 2024-03

### ISSUE THREAD

**Issue by june29** [kairan-app/feeeed#94]
### 概要

アプリケーションが稼働していて、少なくとも自分たちで使う分にはすでに常用できるものになっていて、どこにどんな手を加えるのか脳内で管理するのも困難になってきた (うれしい) ので、月ごとに Issue を用意して整理してみようかな、と思います :bulb:

### やること

- [x] https://github.com/kairan-app/feeeed/pull/98
- [x] https://github.com/kairan-app/feeeed/pull/101
- [x] https://github.com/kairan-app/feeeed/pull/108
- [x] https://github.com/kairan-app/feeeed/pull/106
- [x] https://github.com/kairan-app/feeeed/pull/107
- [x] https://github.com/kairan-app/feeeed/pull/97
- [x] https://github.com/kairan-app/feeeed/pull/102
- [ ] https://github.com/kairan-app/feeeed/pull/126
- [x] https://github.com/kairan-app/feeeed/pull/109
- [x] https://github.com/kairan-app/feeeed/pull/95
- [ ] NotificationWebhook を Discord だけじゃなくて Slack にも通知できるようにする

### 備考

3 月が終わったら 4 月の分の Issue を立てて、積み残しは棚卸ししつつそっちにコピーしたりする。

**Comment by june29** [comment]
NotificationWebhook の最終通知時刻は Redis に保存していたけど、いま Reaction を Pawprint に変える作業をしていて cache の key が変わるな〜面倒だな〜と思って、

https://github.com/kairan-app/feeeed/blob/505a3bd88ae735078549b8ee55adb4cdfb19721f/app/models/notification_webhook.rb#L40-L45

Redis じゃなくて、NotificationWebhook に last_notified_at 的なカラムを生やしてそこに保存するのが素直じゃん？という気分になってきた :thinking:

**Comment by sugiwe** [comment]
こちらありがとうございます😃
デザイン関連も一旦ここにメモしておいて良いでしょうか？
別のIssueにしたほうが良いなど、より良い方法があれば相談して改善していきたいです💪

- [ ] rururu ロゴ を完成させる
- [ ] ロゴをもとにサイトカラーを調整する
- [ ] Pawprintsページ・My Pawprintsページのスタイリングをする
- [ ] トップページの右サイドにRecent Pasprintsを表示させる
- [ ] Pawprintsまわりの第二段階実装のスタイリングをする（figmaで検討しているもの）
- [ ] ナビゲーション周りを整理する
  - [ ] 項目の取捨選択および並べる順番の検討
  - [ ] ログイン/ログアウトボタン・チャンネル登録フォーム・フラッシュメッセージ等の整理

**Comment by june29** [comment]
@sugiwe さん、ありがとうございます！ここを使ってもらって大丈夫です :ok_hand:
これで 3 月を過ごしてみて、よさそうだったら 4 月にも会場をつくってやりくりしてみましょう :relaxed:

**Comment by june29** [comment]
YouTube のフィードを登録しているやつ、Item の画像が This content isn't available な黒いやつになっているのが散見されたので、下記のスニペットを rails console から実行してデータの正常化を図った :memo:

```rb
cs = Channel.where("feed_url LIKE '%youtube.com%'")
cs.each { |c| c.items.each { |i| vid = i.guid.sub("yt:video:", ""); i.update(image_url: "https://img.youtube.com/vi/#{vid}/maxresdefault.jpg") } }
```

YouTube における Video ID 的な文字列がわかればサムネイル画像の URL は機械的に導出できるっぽいので、アプリケーション内のロジック自体をこっちに寄せようかと思っている :dash:

**Comment by june29** [comment]
Pixel 8 Pro で見たとき、画面下部に寄せているメニュー系の UI とページングのリンクたちがケンカするから、なかよく暮らせるように工夫しなきゃ :memo:

![image](https://github.com/kairan-app/feeeed/assets/3970/bdc9d89d-519a-4d57-a27d-06b38273b109)

**Comment by june29** [comment]
Item を並べて表示するときは .order(published_at: :desc) しているのだけれど、これだと、たとえば「数日前の日記を、その日のタイムスタンプで投稿しました」ってときに気づきにくい。

created_at は新しいが published_at はそんなに新しくない、という新着 Item をどう表示していくといいだろう :thinking:

あんまり「未読管理」っぽい雰囲気は出したくないのだけれど、Inbox を整えて「Paw 済み」「Skip 済み」のやつは非表示にする、みたいな制御ができると、新着 Item は新着 Item として目に触れやすくはなるだろう。Inbox はこういう「機能的」なページという位置づけにして、まともな未読管理をできる場所にしてあげてもいいのかもな〜。

**Comment by june29** [comment]
- https://github.com/kairan-app/feeeed/pull/106
- https://github.com/kairan-app/feeeed/pull/107
- https://github.com/kairan-app/feeeed/pull/108
- https://github.com/kairan-app/feeeed/pull/109

体が空いたので「やれば終わるやつだから、とにかくやりなさいよ」系をドドドと終わらせたぞ〜。次はどれをやろうかな、考えて進めていきますね :relaxed:

**Comment by june29** [comment]
Discord には「Slack-compatible Webhook」があるので、先に Slack 用の通知処理をつくれば Discord にも流用できたか… :innocent:
https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook

**Comment by june29** [comment]
いっぱい進んだ 3 月でしたね！ 4 月 https://github.com/kairan-app/feeeed/issues/128 もよろしくお願いします :raised_hands:
